on: [push]
name: "test"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
          - os: windows-2022
          #- os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install curl
        run: choco install autoconf automake libtool --source cygwin -y --force
        if: matrix.os == 'windows-2022'
      - name: Install dep
        run: brew install autoconf automake libtool
        if: matrix.os == 'macos-latest'
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install autoconf -y
        if: matrix.os == 'ubuntu-latest'
      - name: Build curl
        run: |
          cd curl
          autoreconf -fi
          ./configure --without-ssl
          make
        if: matrix.os != 'windows-2022'
      - name: Build curl (windows)
        run: |
          C:\tools\cygwin\bin\bash.exe -l -c ^"cd curl ^&^& autoreconf -fi ^&^& ./configure --without-ssl ^&^& make loadable ^"
        if: matrix.os == 'windows-2022'
      - name: Build + Test
        run: |
          mkdir -p dist/
          make loadable
          make test-loadable
