on: [push]
name: "test"
jobs:
  test-macos:
    name: Testing on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install deps
        run: brew install autoconf automake libtool
      - name: Build curl
        run: |
          cd curl
          autoreconf -fi
          ./configure  --without-brotli --without-libpsl --without-nghttp2 --without-ngtcp2 --without-zstd --without-libidn2 --without-librtmp --without-zlib --without-ssl
          make
      - name: Build + Test
        run: |
          mkdir -p dist/
          make loadable
          make test-loadable
  test-ubuntu:
    name: Testing on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install autoconf -y
      - name: Build curl
        run: |
          cd curl
          autoreconf -fi
          ./configure  --without-brotli --without-libpsl --without-nghttp2 --without-ngtcp2 --without-zstd --without-libidn2 --without-librtmp --without-zlib --without-ssl
          make
      - name: Build + Test
        run: |
          mkdir -p dist/
          make loadable
          make test-loadable

#  test-windows:
#    name: Testing on Windows
#    runs-on: windows-2022
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#      - name: Install deps
#        run: choco install autoconf automake libtool --source cygwin -y --force
#      # TODO this is not fun
#      - name: Build curl (windows)
#        run: |
#          C:\tools\cygwin\bin\bash.exe -l -c ^"cd curl ^&^& autoreconf -fi ^&^& ./configure --without-ssl ^&^& make loadable ^"
#      - name: Build + Test
#        run: |
#          mkdir -p dist/
#          make loadable
#          make test-loadable
