on: [push]
name: "test"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install curl
        run: choco install curl -y --force
        if: matrix.os == 'windows-2022'
      - name: Install curl
        run: apt-get install curl -y
        if: matrix.os == 'ubuntu-latest'
      - name: Build + Test
        run: |
          mkdir -p dist/
          make loadable
          make test-loadable
